"""Shared fixtures: SYNTHETIC hands only (generated by code; non-identifying)."""

from __future__ import annotations

import pytest
from pandit_contracts.palm import HandSide

from pandit_palm_vision.synthetic import SyntheticPalm, make_synthetic_palm


@pytest.fixture(scope="session")
def right_palm() -> SyntheticPalm:
    return make_synthetic_palm(HandSide.RIGHT, seed=1)


@pytest.fixture(scope="session")
def left_palm() -> SyntheticPalm:
    return make_synthetic_palm(HandSide.LEFT, seed=2)
