"""Test helpers: SYNTHETIC hands only (generated by code; non-identifying)."""

from __future__ import annotations

from typing import Any

from pandit_palm_vision.hand import StaticHandDetector
from pandit_palm_vision.image_input import CaptureContext
from pandit_palm_vision.pipeline import PalmPipeline
from pandit_palm_vision.quality import fixture_quality_config
from pandit_palm_vision.synthetic import SyntheticPalm

PALM_FACING = CaptureContext(mirrored=False, palm_facing=True)


def pipeline_for(palm: SyntheticPalm, **kwargs: Any) -> PalmPipeline:
    """A pipeline with the fixture-only quality config and a detector that returns the palm."""
    detector = StaticHandDetector((palm.candidate(assumes_mirrored=False),), False)
    return PalmPipeline(detector, quality_config=fixture_quality_config(), **kwargs)
